version: '3'
services: 
  nginx:
    image: nginx:latest
    volumes:
      - ./templates:/etc/nginx/templates
      - ./ssl:/etc/ssl
    env_file: ../.env
    ports:
      - 80:80
      - 443:443
      - 8080:8080

